Course_django2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Course_django2 import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('photologue/', include('photologue.urls', namespace='photologue')),

    path("news/", include("news.urls")),
    path("contact/", include("contact.urls")),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("", PostList.as_view(), name="news"),
    path("search/", Search.as_view(), name="search_form"),
    path("<slug:category>/", PostList.as_view(), name="category_post"),
    path("<slug:category>/<slug:slug>/", PostDetail.as_view(), name="post_detail"),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """Модель категорий статей"""
    name = models.CharField("Имя", max_length=100)
    slug = models.SlugField("url", max_length=100)
    pagination = models.PositiveIntegerField('Кол. для пагинации', default=5)
    template = models.CharField(
        'Используемый шаблон',
        max_length=100,
        blank=False,
        default='news/post-list.html'
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )
    # parent = models.ForeignKey(
    #     'self',
    #     verbose_name="Категория",
    #     on_delete=models.SET_NULL,
    #     null=True,
    #     blank=True
    # )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_post', kwargs={"category": self.slug})

    class Meta:
        verbose_name = "Категория статей"
        verbose_name_plural = "Категории статей"


class Tag(models.Model):
    """Модель тегов"""
    name = models.CharField("Имя", max_length=100)
    slug = models.SlugField("url", max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class Post(models.Model):
    """Статьи"""
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    title = models.CharField("Заголовок", max_length=100)
    subtitle = models.CharField('Подзаголовок', max_length=100, blank=False, default='')
    mini_text = models.TextField("Краткое содержание", max_length=1000, default='')
    text = models.TextField("Текст")
    image = models.ImageField('Главное изображение', upload_to='post/', blank=True)
    gallery = models.ForeignKey(
        'photologue.Gallery',
        verbose_name="Галерея",
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    created = models.DateTimeField("Дата создания", auto_now_add=True)
    edit_date = models.DateTimeField(
        "Дата редактирования",
        default=timezone.now,
        blank=True,
        null=True
    )
    published_date = models.DateTimeField(
        "Дата публикации",
        default=timezone.now,
        blank=True,
        null=True)
    category = models.ForeignKey(
        Category,
        verbose_name="Категория",
        on_delete=models.SET_NULL,
        null=True
    )
    tags = models.ManyToManyField(Tag, verbose_name="Теги")
    published = models.BooleanField("Опубликовать?", default=True)
    status = models.BooleanField("Для зарегистрированных", default=False)
    slug = models.SlugField("url", max_length=100)
    viewed = models.PositiveIntegerField("Просмотров", default=0)

    def __str__(self):
        return self.title

    def get_comments(self):
        return Comment.objects.filter(post_id=self.id)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={"category": self.category.slug, "slug": self.slug})

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["-created"]


class Comment(models.Model):
    """Модель комментариев к статье"""
    post = models.ForeignKey(
        Post,
        verbose_name="Статья",
        on_delete=models.CASCADE
    )
    text = models.TextField("Комментарий")
    moderation = models.BooleanField("Разрешено к публикации", default=False)
    created = models.DateTimeField("Дата написания", auto_now_add=True)

    def __str__(self):
        return "{}".format(self.post.title)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ["-created"]

news/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    """Форма комментариев"""
    class Meta:
        model = Comment
        fields = ("text",)
        # exclude = ("post",)
        widgets = {
            "text": forms.Textarea(attrs={"rows": 15, "cols": 5, "class": "text-text"})
        }

news/views.py
from datetime import datetime

from django.db.models import Q
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import Post, Category, Comment
from .forms import CommentForm


class PostList(ListView):
    """Список статей"""
    context_object_name = 'posts'

    def get_queryset(self):
        if self.kwargs.get('category') is not None:
            post_list = Post.objects.filter(
                category__slug=self.kwargs.get('category'),
                published=True,
                published_date__lte=datetime.now(),
            )
            if self.request.user.is_authenticated:
                posts = post_list
            else:
                posts = post_list.filter(status=False)

            if posts.exists():
                self.paginate_by = posts.first().category.pagination
                self.template_name = posts.first().category.template
        else:
            posts = Post.objects.all()
            self.paginate_by = 2
            self.template_name = 'news/post-list.html'
        return posts
        # else:
        #     raise Http404


class PostDetail(DetailView):
    """Вывод полной статьи"""
    model = Post
    template_name = 'news/post-detail.html'

    # def get_queryset(self):
    #     post = Post.objects.get(
    #             slug=self.kwargs.get('slug'),
    #             published=True,
    #             published_date__lte=datetime.now(),
    #         )
    #     return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context

    def post(self, request, category, slug):
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post = Post.objects.get(slug=slug)
            form.save()
            return HttpResponseRedirect(reverse('post_detail', kwargs={"category": category, "slug": slug}))
        else:
            return HttpResponse(status=400)


class Search(View):
    """Поиск по статья и ктегориям"""
    def get(self, request):
        search = request.GET.get("search", None)
        context = Post.objects.filter(Q(title__icontains=search) |
                                      Q(category__name__icontains=search))
        # if not context.exists():
        #     context = Post.objects.filter(category__name__icontains=search)
        return render(request, 'news/post-list.html', {"posts": context})


class CategoryPost(ListView):
    """"""
    template_name = "shop/list-product.html"
    paginate_by = 5

    def get_queryset(self):
        slug = self.kwargs.get("slug")
        node = Category.objects.get(slug=slug)
        if Post.objects.filter(category__slug=slug).exists():
            posts = Post.objects.filter(category__slug=slug)
        else:
            posts = Post.objects.filter(category__slug__in=[x.slug for x in node.get_family()])
        return posts

templates/news/base.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-md-8">
        {% block post %}

        {% endblock post %}
    </div>
    {% include 'include/sidebar.html' %}
{% endblock content %}

templates/news/left_posts.html
{% for post in list_post %}
    <h5><a style="color: red;" href="{% url 'post_detail' pk=post.id %}">{{ post.title }}</a></h5>
{% endfor %}

templates/news/post-detail.html
{% extends 'news/base.html' %}
{% load  category_tag bootstrap4 %}
{% block post %}
    <h1 class="my-4">{{ post.title }}
        <small>{{ post.subtitle }}</small>
    </h1>
    <div class="card mb-4">
        {% if post.image %}
            <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
            <p class="card-text">
                {{ post.text }}
            </p>
            <p>
                {% for photo in post.gallery.photos.all %}
                    <img src="{{ photo.image.url }}">
                {% endfor %}
            </p>
        </div>
        <div class="card-footer text-muted">
            <a href="#">Start Bootstrap</a>
        </div>
    </div>
    <h3>Коментарии</h3>
    {% for comment in post.get_comments %}
        {{ comment.text }}
    {% endfor %}
    {% if user.is_authenticated %}
        <form action="{{ post.get_absolute_url }}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit">Отправить</button>
        </form>
    {% endif %}
    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
        </li>
    </ul>
{% endblock post %}

templates/news/post-list-python.html
{% extends 'base.html' %}
{#{% load  category_tag %}#}
{% block content %}
    {% for post in posts %}
        <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
{#        <h5>{{ post.subtitle }}</h5>#}
        {% if post.image %}
            <img src="{{ post.image.url }}" style="width: 400px; height: 300px;">
        {% endif %}
        <p>{{ post.mini_text }}</p>
        <b>{{ post.published_date }}</b>
    {% endfor %}
    <hr>
    {#    {% category_list %}#}
{% endblock content %}

templates/news/post-list.html
{% extends 'news/base.html' %}
{% load mptt_tags bootstrap4 %}
{% block post %}
    <h1 class="my-4">Page Heading
        <small>Secondary Text</small>
    </h1>

    {% for post in posts %}
        <!-- Blog Post -->
        <div class="card mb-4">
            {% if post.image %}
                <img class="card-img-top" src="{{ post.image.url }}">
            {% endif %}
            <div class="card-body">
                <h2 class="card-title">{{ post.title }}</h2>
                <small class="card-title">{{ post.subtitle }}</small>
                <p class="card-text">
                    {{ post.mini_text }}
                </p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
                <small>{{ post.published_date }}</small>
                {% for tag in post.tags.all %}
                    <a href="#">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <!-- Pagination -->
{#    <ul class="pagination justify-content-center mb-4">#}
{#        <li class="page-item">#}
{#            <a class="page-link" href="#">&larr; Older</a>#}
{#        </li>#}
{#        <li class="page-item disabled">#}
{#            <a class="page-link" href="#">Newer &rarr;</a>#}
{#        </li>#}
{#    </ul>#}
    {% bootstrap_pagination page_obj pages_to_show=5 %}
{% endblock post %}